export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_EXITO = 'VALIDAR_EXITO';
export const VALIDAR_ERROR = 'VALIDAR_ERROR';

export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_EXITO = 'AGREGAR_EXITO';
export const AGREGAR_ERROR = 'AGREGAR_ERROR';


